### ISSUE TITLE
Hook up syntax errors to the editor

### ISSUE THREAD

**Issue by null-a** [probmods/webppl-editor#10]
This came up during summer school planning. I'm not sure exactly what can be done, but I think the idea is to make use of the extra information we'll get from probmods/webppl#292 and probmods/webppl#314.

**Comment by ngoodman** [comment]
now that source locations are available for errors (PR #425), it would be nice to hook up the editor to highlight were an error occurred (as we did in webchurch).

**Comment by null-a** [comment]
A few comments/thoughts I had while working on this:
- The only difference that will be noticeable from the editor once probmods/webppl#425 is merged is that errors raised in `.wppl` code will have an extra `sourceMaps` property available. See [here](https://github.com/probmods/webppl/pull/425/files#diff-5c8b199a98cb05fcfa67ad0a331c165bR48) for how this is used when running under Node.
- It may be that we can do _some_ pre-processing of this information in webppl's `browser.js`. We should do this where we can to avoid duplicating code. However, I don't think _everything_ can happen there. For example, there are some things you can imagine wanting to implement that will need a source map of the whole browser bundle, so this would have to happen _outside_ of webppl core.
- probmods/webppl#425 doesn't fix-up stack traces, so for now it's only possible to highlight errors throw directly from user code.

**Comment by longouyang** [comment]
Now that probmods/webppl#472 is merged, I've gotten basic highlighting working in eb20373

(see demo page: http://probmods.github.io/webppl-editor/)

It'd be nice if error positions had both a start column number and an end column number (currently I'm just highlighting from the start column number to the end of the line). Would that be hard to build into `compile`?

**Comment by null-a** [comment]
Neat!

I guess there are a few different things we could mean by the end column, and getting at some of those might be quite involved.

One thing we could try to do is improve the case where the position points to an identifier, by highlighting only that identifier. Conveniently, when we look up the original location in the source map, it appears we're already given the name of the identifier at that position in the original code. (But only in those cases where there _is_ an identifier in this position -- there may not be.) So, in your 'tricky reference' demo, I think `originalPosition.name` would be `'tricky'` at [this point](https://github.com/probmods/webppl-editor/commit/eb203734054911b487641b229bcd4cb16a2527b6#diff-1fdf421c05c1140f6d71444ea2b27638R81).

This approach won't avoid highlighting the entire line in some cases, but it might be something that works fairly often while still been simple to implement?

Also, note that this will only work for code for which we use source maps to get back to original locations. Since we're only highlighting code in the user's program in the editor, that seems fine though?

**Comment by null-a** [comment]
At present, the demos don't work in Safari, and possibly only work in Chrome. The problem is that the `stack-trace` library we use with Node is v8 specific. In the browser, perhaps [stacktrace.js](https://github.com/stacktracejs/stacktrace.js) can help?

**Comment by longouyang** [comment]
Ah -- thanks for the tip on the identifiers. I've added identifier highlighting in eeb3208

`stacktrace-js` doesn't look like it'll work for us -- it appears to give different line numbers in Chrome than `stack-trace`. I'll investigate more.

**Comment by null-a** [comment]
I spotted a bug in the source map stuff in webppl, the fix is probmods/webppl#477. I expect a similar change needs to be made in the editor too.

**Comment by longouyang** [comment]
Do you have an example of where plain JS errors would be incorrectly mapped to the wppl file? (so I can make sure I've implemented correctly)

**Comment by null-a** [comment]
I could come up with a reproduction in Node, but when that's bundled/browserified the line numbers change and it will likely work without error once in the browser.

If your implementation (1) has the same structure and the PR (returning `firstStackFrame` when the function name doesn't start with `eval`, and using the source map otherwise), and (2) it works for errors from js and wppl code then I think we're good.

It's possible to craft an example specifically for the browser if we really need to, but it's a bit fiddly and I'd rather not spend time doing that right now. Can we make do for now and see where we end up once we have stack traces and have done any consolidating of the logic currently duplicated across the editor and node?

**Comment by longouyang** [comment]
Fair enough.

Question: Currently in editor, `firstStackFrame` is actually [the first stack frame where `fileName == '<anonymous>'`](https://github.com/probmods/webppl-editor/blob/master/src/index.js#L58) (it's only useful to highlight code that's actually in the code box). Does this affect how I would port over #477?

**Comment by null-a** [comment]
> Does this affect how I would port over #477?

Ah! Yes, I think it means you don't have to. The problem under node was that we were sometimes passing line/cols numbers of errors originating in JS code into `originalPositionFor` which is wrong because the source map only has info about webppl code. Your `findWhere` looks like it ensures you'll only be passing positions relating to webppl code into `originalPositionFor`, so I think you're good.

**Comment by longouyang** [comment]
Okay, sounds good.

Now that basic error highlighting is in place, I'll close this issue and open a new one just for parsing stack errors in non-Chrome browsers.
