### ISSUE TITLE
Editing slows down for larger code boxes

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl-editor#24]
For a model with ~3800 characters (~500 words), there is already a small but noticeable delay between typing and characters appearing.

**Comment by longouyang** [comment]
I haven't been able to reproduce this on the webppl-editor demo page, can you help me reproduce this?

**Comment by stuhlmueller** [comment]
If I paste [this code](https://gist.github.com/stuhlmueller/1e3b20ba9af98cfa7b3975a5dc219a29) in, it's a little slow for me. If I paste it in twice, it's quite slow. If I paste it in three times, it's basically unusable.

**Comment by longouyang** [comment]
I tried that on the demo hosted at http://probmods.github.io/webppl-editor (Chrome 50, incognito mode)

It felt slightly slow for three pastes but certainly not unusable. Can you try the workflow I suggested? (I wonder if some extension is interacting in a weird way).

**Comment by stuhlmueller** [comment]
On that page, with Chrome, incognito mode, no extensions, three pastes, it's still pretty slow (not really noticeable if I type a single character, but very obvious if I type a sentence). Six pastes is unusable.

**Comment by longouyang** [comment]
Fixed in 320c071 (I was updating the `CodeEditor`'s `code` state whenever the `react-codemirror` component updated but this was both unnecessary and slow)
