### ISSUE TITLE
Cleanup happening too early in some models?

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl-editor#27]
If I run the following model [on the editor test page](https://probmods.github.io/webppl-editor/)...

```
var myDraw1 = Draw(200, 200, true);
loadImage(myDraw1, "http://dippl.org/assets/img/the_scream.jpg");

var myDraw2 = Draw(200, 200, true);
loadImage(myDraw2, "http://dippl.org/assets/img/box.png");
```

...I observe this error in the console:

```
Uncaught TypeError: resumeTrampoline is not a function
Obj.onload @ draw.js:116
```

**Comment by longouyang** [comment]
Sort of.

If the last continuation is `topK`, then we do indeed cleanup too early, because `topK` is `endJob`:

``` js
var myDraw1 = Draw(200, 200, true);
loadImage(myDraw1, "http://dippl.org/assets/img/the_scream.jpg");
```

But the error goes away if we do:

```
var myDraw1 = Draw(200, 200, true);
loadImage(myDraw1, "http://dippl.org/assets/img/the_scream.jpg");
flip()
```

I've fixed the `loadImage` call to `resumeTrampoline` in 0b414e4 so that we avoid running `topK` prematurely

**Comment by stuhlmueller** [comment]
Thanks!
