### ISSUE TITLE
special color for factor-like keywords

### ISSUE THREAD

**Issue by ngoodman** [probmods/webppl-editor#39]
just for the sake of quickly seeing where data/conditions happen in a model, it'd be nice if `factor`, `condition`, and `observe` had a special color.

while we're at it, i guess `sample` could also have a special color. (but then there's the natural desire for the sampling helpers like `gaussian` to be colored... maybe too that's much.)

**Comment by ngoodman** [comment]
bump. @longouyang, how hard would this be?

**Comment by longouyang** [comment]
easy enough. what keywords and color would you like?

fwiw, i think just using bold is nice:

![screen shot 2016-09-22 at 12 16 59 pm](https://cloud.githubusercontent.com/assets/14802/18762640/7d7b7fce-80be-11e6-9f93-be3548136f3f.png)

**Comment by longouyang** [comment]
Closed by b3e64d7
