### ISSUE TITLE
parser.setReadtable is not a function (Jupyter)

### ISSUE THREAD

**Issue by tbenst** [probmods/webppl-editor#41]
I'm attempting to add webppl to a (python) Jupyter notebook using an admittedly hacky method.

![webppl-jupyter](https://cloud.githubusercontent.com/assets/863327/18450398/b4bfab6a-78e7-11e6-9a3d-7b40aac90927.png)

Unfortunately I get the following error from webppl: `TypeError: parser.setReadtable is not a function`. Any thoughts or an alternate suggested method? Thanks!

**Comment by longouyang** [comment]
I suspect this is a webppl issue, not webppl-editor; `parser.setReadtable` is a function inside sweet.js, which is a library that webppl uses.

I'm a little wary of this approach to embedding webppl inside Jupyter; it seems like it'd be much cleaner to write a proper Jupyter kernel (though I know that would be more effort)

**Comment by tbenst** [comment]
Just took a stab at this. Tried [this node.js kernel](https://github.com/notablemind/jupyter-nodejs/) in docker using [this Dockerfile](https://github.com/nodejs/docker-node/issues/10) but was stymied by [an error running node install](https://github.com/notablemind/jupyter-nodejs/issues/19). Will try again next week

**Comment by tbenst** [comment]
Okay, some progress: can now install webppl and import in jupyter ([docker image](https://hub.docker.com/r/tbenst/jupyter-webppl/)) Haven't been able to run any webppl code yet (below). Apologies if this is in the documentation somewhere and i missed it

![image](https://cloud.githubusercontent.com/assets/863327/18823379/58fd8194-836e-11e6-824d-664653edfa53.png)

**Comment by longouyang** [comment]
`webppl.prepare` takes two mandatory arguments, the compiled code and a continuation, and an optional objects argument:

``` js
webppl.prepare(
  compiled, // code
  function(s,x) { }, // continuation that does something with the return val x
  {initialStore: {observedData: [1,2,3]}}) // options; here, I'm setting the initial contents of globalStore
```

**Comment by longouyang** [comment]
(Oh, and btw, this compile/prepare/run stuff isn't documented anywhere yet as far as I know)

**Comment by tbenst** [comment]
Thanks!

Turns out that node.js kernel does not supply cell magics for use with python or another kernel. Seems that Beaker is a better option than jupyter here.

I created a fork of beaker notebook and added webppl as a language: https://github.com/tbenst/beaker-notebook. This is already improved over the previous jupyter example as the compile command happens on the node.js backend. 
![image](https://cloud.githubusercontent.com/assets/863327/18861785/b98fa2d4-843c-11e6-9f8c-4d4ce7d8f6dc.png)

The main limitation is I've yet to implement auto-translation. Any thoughts on how i might include the [beaker object](https://github.com/tbenst/beaker-notebook/blob/master/plugin/webppl/src/dist/app/beaker-object.js) in webppl?

Another thought is to add globalStore to the beaker object, and to always initialize webppl with initialStore = beaker.globalStore, and to pass globalStore back after execution & update beaker.globalStore.

**Comment by longouyang** [comment]
Nice!

I'm a little unclear on what the interface for the beaker object is. Where is a `beaker` global variable available -- inside the node.js backend? And what methods do you call on it to make the auto-translation happen?

**Comment by tbenst** [comment]
The beaker object is available in most languages: https://github.com/twosigma/beaker-notebook/wiki/Auto-Translation.  The object is global across a notebook. The key feature is you can get and set variables from cells with  different languages

**Comment by longouyang** [comment]
In this case, I think that your backend code should call `prepare` with a continuation that uses `beaker` to do the auto translation on the return value of the webppl program.

**Comment by tbenst** [comment]
cool, got it working:
![webppl](https://raw.githubusercontent.com/tbenst/beaker-webppl/master/doc/webppl-Example.png)

should now be usable with this functionality. `docker run -it -p 8800:8800 tbenst/beaker-webppl`
