### ISSUE TITLE
Syntax error formatting

### ISSUE THREAD

**Issue by null-a** [probmods/webppl-editor#43]
Once probmods/webppl#675 is merged, program code will no longer be parsed by sweet.js. I've tested this change with the editor to make sure that the bit where you parse exception text for syntax errors hasn't broken. As far as I can see (though you may want to check) it still basically works, although there may be a small problem with formatting:

![editor-current](https://cloud.githubusercontent.com/assets/9109012/19389610/793cacde-921c-11e6-8dc5-92276e2147d9.png)
![editor-new](https://cloud.githubusercontent.com/assets/9109012/19389620/8470d620-921c-11e6-8328-b38332c44ab9.png)

(Update: I've just noticed that the line number reported for syntax errors differs by 1 following this change. See the example in the webppl PR.)

On the plus side, it looks like this PR fixes your 'syntax - hanging dot' todo from the editor demo page.

**Comment by longouyang** [comment]
Fixed by 93be502
