### ISSUE TITLE
Check if WebPPL is available; while it is not, disable the run button

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl-editor#5]
WebPPL is a big library and takes a while to load (and, in the current version, to compile packages as well). Pages that include code boxes would look better if the code blocks could immediately be transformed into CodeMirror boxes, even if WebPPL isn't available yet.

**Comment by longouyang** [comment]
Added in b34e01c

See compiled/index.html for a usage example

I decided to make it so that the run button even works while webppl is unavailable; clicking it changes the status to "loading webppl" until webppl is loaded

Does this work for you?

**Comment by stuhlmueller** [comment]
Yes, this is perfect.
